# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            dwils098
tagline:          'A Memory Dump'
description:      'Simple repository of my thoughts.'
baseurl:          'http://dwils098.github.io/'
paginate:         5

author:
  name:           'Dany Wilson'
  url:            https://twitter.com/dwils098

# Custom vars
version:          1.0.0

github:
    repo: http://github.com/dwils098/

